version: '3'
services:
  postgres:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=authentication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=135791
    volumes: 
      - /Users/tmota/devel/teach/__23FCS3250_SE/activities/activity-20-docker-compose/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s 
  myapp:
    build: .
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
  
  